mutation UpdateTransaction (
  $id: String!,
  $user_id: String,
  $description: String,
  $merchant_id: String,
  $debit: Boolean,
  $credit: Boolean,
  $amount: Float
) {
    updateTransaction (
      id: $id,
      user_id: $user_id,
      description: $description,
      merchant_id: $merchant_id,
      debit: $debit,
      credit: $credit,
      amount: $amount,
    ) {
      id
    }
}