query GetMerchants {
  merchants {
    id
    name
    transactions {
      id
      description
      amount
      debit
      credit
      date
      category {
        id
        name
      }
      user {
        id
        firstName
        lastName
      }
    }
  }
}
