query GetTransactions {
  transactions {
    id
    amount
    credit
    debit
    description
    category {
      id
      name
    }
    merchant {
      id
      name
    }
    user {
      id
      firstName
      lastName
      dob
    }
  }
}
