query GetUsers {
  users {
    id
    firstName
    lastName
    dob
    transactions {
      id
      amount
      description
      debit
      credit
      category {
        id
        name
      }
      merchant {
        id
        name
      }
    }
  }
}
